### PR TITLE
Markdown

### PR DESCRIPTION
**Pull request by underr**

### CODE REVIEW

**Comment by phikal** [comment]
All good, thank you for contributing!

**Comment by phikal** [comment]
Just asking, what exactly was is the point of the `sanitize` option? If it and markdown are not set, nothing will happen. As far as I see it, it seems to be a double option confirmation.

**Comment by underr** [comment]
If you remove `config.markdown` from the conditional, this happens:

```
marked.setOptions({ sanitize: true });
^
ReferenceError: marked is not defined
```

Because if **only** sanitize is `true` it would call the `marked` variable, and `marked` wouldn't be declared. If you just leave `(config.markdown)` there, it will enable sanitize even if you don't want to.

But to tell the truth, I don't see the point of enabling HTML input on a IB, so it could be just enabled by default.

**Comment by phikal** [comment]
I pushed a commit a while ago, which seems to work and only has one option, take a look at it if you want to. Seems to work.

**Comment by underr** [comment]
Looks nice.

I'll ask this here because it's not important: why is theming listed on the TODO list?
Shouldn't that be handled by client?

**Comment by phikal** [comment]
Yes, but the server could define colours which the client would use.

It would of course be optional for the client to use, but if it would want to use it, it would check `GET:/` to get the `theme` attribute, containing a JSON object, which specifies the colours something like this:

``` JSON
"theme": {
    "main" : "#ffcc00",
    "highlight" : "#ff00cc",
    "link" : "#00ffcc",
    "other" : "more stuff to be defined"
}
```

**Pull request merged**
