### PR TITLE
Optionalize image serving

### PR DESCRIPTION
**Pull request by underr**
Express isn't recommended for serving static files; on a production environment that should be done by something like nginx.

### CODE REVIEW

**Comment by phikal** [comment]
A feature I am going to start working on will the implementing CDN services, but this is good too. But could you default it to true for now? Not just in `config.sample.json` but in `app.js`?

**Comment by underr** [comment]
How so?

**Comment by phikal** [comment]
Never mind, I'll do it myself.

**Comment by phikal** [comment]
see: ca97ca74cb21c624881737046cd8d27701d1b701

**Pull request merged**
